//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Log = new HashSet<Log>();
            this.WebSiteInbox = new HashSet<WebSiteInbox>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string WebLogin { get; set; }
        public string WebPassword { get; set; }
        public string VTigerUsername { get; set; }
        public string VTigerUrl { get; set; }
        public string VTigerAccessKey { get; set; }
        public Nullable<bool> IsVTigerOK { get; set; }
        public string EconomicPublicAPI { get; set; }
        public string EconomicPrivateAPI { get; set; }
        public Nullable<bool> IsEconomicOK { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> ForceNewProduct { get; set; }
        public Nullable<bool> ForceNewDebtor { get; set; }
        public bool IsWriteToLogFile { get; set; }
    
        public virtual ICollection<Log> Log { get; set; }
        public virtual ICollection<WebSiteInbox> WebSiteInbox { get; set; }
    }
}
